### ISSUE TITLE
Convert alerts to notifications

### ISSUE THREAD

**Issue by MegaphoneJon** [4ndygu/civicrm_osdi#16]
I'm happy to do this, or you can Andy.  Instead of using `alert` in JS for notifications, we should instead use [CiviCRM notifications](https://docs.civicrm.org/dev/en/latest/framework/ui/#notifications-and-confirmations).  It shouldn't take more than a few minutes to change `alert` to `CRM.alert`, plus add a status to differentiate between success/warning/error.

**Comment by 4ndygu** [comment]
ill clean this on the wknd!

**Comment by 4ndygu** [comment]
fixed.
