### ISSUE TITLE
Use EntityRefs for Group ID and Rule ID

### ISSUE THREAD

**Issue by MegaphoneJon** [4ndygu/civicrm_osdi#17]
It will give a much better end-user experience if users can select dedupe rules and groups from a list, rather than typing in their IDs.  Fortunately, there's a helper function to handle this: https://docs.civicrm.org/dev/en/latest/framework/quickform/entityref/#js-add-from-client-side

Again, I'm happy to submit the PR but the others need to be merged first to avoid merge conflicts.

**Comment by 4ndygu** [comment]
I have no idea how to do this, but I think its a better exercise if I work on this on the weekend !

**Comment by MegaphoneJon** [comment]
OK! Now that #14 is merged, I might just do it myself, it's pretty quick.

**Comment by 4ndygu** [comment]
great! appreciate it :).
