### ISSUE TITLE
Editing Schedule Job can break loading of Jobs page

### ISSUE THREAD

**Issue by seamuslee001** [4ndygu/civicrm_osdi#33]
We edited one of the scheduled jobs through the scheduled job UI (Admin -> Scheduled Jobs -> Edit) and we managed to add in a carriage return to the groups param. This then borked the API call in the OSDIJob.php page (L50) because it then treated the group id as a string rather than as an Integer. CiviCRM APIv3 on Group.Get verifies that the id column is an int or it throws error

**Comment by johntwyman** [comment]
@seamuslee001 has raised #34 to resolve this.

**Comment by 4ndygu** [comment]
gotcha, thanks!
