### ISSUE TITLE
"Remote Time Zone" is local time zone?

### ISSUE THREAD

**Issue by MegaphoneJon** [4ndygu/civicrm_osdi#8]
Hi Andy,

It looks from your docs like the item labeled "Time Zone of remote server" is actually the "time zone on the server where the civicrm instance is running" - or what I'd consider the local time zone.  Am I understanding correctly?  If so, could we just update the labels appropriately?  If I'm misunderstanding, let's see if we can figure out some language that makes it clearer.

Thanks,
Jon

**Comment by 4ndygu** [comment]
label should be updated. Do let me know and close if it works for you

**Comment by MegaphoneJon** [comment]
The input label was changed but not the button label.  I revamped the template for the configuration page and took care of it as part of that.
