### ISSUE TITLE
"install_groupid" and "install_matching" issues

### ISSUE THREAD

**Issue by MegaphoneJon** [4ndygu/civicrm_osdi#9]
Hi Andy,

I know you're done, but you said you'd be available for bugfixes.  Let me know if you think this isn't something you'll get to.

In the code I noticed a couple of things about these two functions.
* They're called by the "enable" and "postInstall" hooks.  If I understand them correctly, they should just run once, on `hook_civicrm_install`.
* They don't have docblocks, so I'm actually not 100% sure.  I see that `install groupid` creates the custom field group and field; I haven't investigated what `install_matching` does, but if you could add a docblock, it would help future maintainers of the code.
* `hook_civicrm_uninstall` should have functions that reverse these functions (e.g. delete the custom field and group).

Thanks,
Jon

**Comment by 4ndygu** [comment]
Do you feel like someone who disables and enables the application should have any functionality trigger?

**Comment by MegaphoneJon** [comment]
No - disable/enable don't typically change the installed data.  A good user story for disable/enable is "I think there's a bug in this extension that's causing a problem elsewhere in CiviCRM, let me turn it off for a minute to test".  They would expect to be able to re-enable and resume where they left off.

Someone who uninstalls would ideally like all traces of the extension removed.  This is particularly important because the extension won't reinstall cleanly in its current state.

**Comment by 4ndygu** [comment]
makes sense to me - i merged some code which will delete everything installed, adds code blocks to the functions and the install functions, and moves all this behavior into the install hook.

https://github.com/4ndygu/civicrm_osdi/pull/10/files

**Comment by MegaphoneJon** [comment]
This looks good!  With one exception of a typo, which I've submitted a PR for in #11.
